# Generated by Django 5.0.7 on 2024-07-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('restaurants', '0003_restaurant_content_restaurant_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='images',
            field=models.ManyToManyField(related_name='restaurants', to='core.image'),
        ),
    ]
