# Generated by Django 5.0.7 on 2024-07-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('owner', 'Owner')], default='regular', max_length=10),
        ),
    ]
