# Generated by Django 5.0.7 on 2024-11-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_code_generated_at_customuser_is_verified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="code_generated_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="verification_code",
        ),
    ]
