# Generated by Django 5.0.7 on 2024-11-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_smscode_remove_customuser_code_generated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("verification_code", models.CharField(max_length=6)),
                ("message_id", models.CharField(max_length=100, unique=True)),
                ("status", models.CharField(default="queued", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="SMSCode",
        ),
    ]
