repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.10.1'
    hooks:
    -   id: isort

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.6.0'
    hooks:
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.4'
    hooks:
    -   id: autopep8