# Generated by Django 5.0.7 on 2024-07-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_alter_attraction_options_remove_attraction_images_and_more'),
        ('core', '0001_initial'),
        ('entertainments', '0004_alter_entertainment_options_and_more'),
        ('hotels', '0005_alter_hotel_options_remove_hotel_images_hotelimage'),
        ('regions', '0005_alter_region_options_remove_region_images_and_more'),
        ('restaurants', '0005_alter_restaurant_options_remove_restaurant_images_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
