# Generated by Django 5.0.7 on 2024-07-16 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='entertainment_images/')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entertainments', to='regions.region')),
            ],
        ),
    ]
