# Generated by Django 5.0.7 on 2024-11-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entertainment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField(auto_now_add=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="content_images/"
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=255, null=True)),
                ("seo_description", models.TextField(blank=True, null=True)),
                ("address", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "Достопримечательность",
                "verbose_name_plural": "Достопримечательности",
            },
        ),
        migrations.CreateModel(
            name="EntertainmentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="ReviewEntertainment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Оценка от 1 до 5, где 1 - плохо, а 5 - отлично.",
                        null=True,
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Текстовый комментарий к месту развлечения или гостинице. Пользователь может оставить свой отзыв.",
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания отзыва.",
                        verbose_name="Дата отзыва",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Опциональное изображение, которое можно прикрепить к отзыву.",
                        null=True,
                        upload_to="content_images/",
                        verbose_name="Изображение отзыва",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв о развлечении",
                "verbose_name_plural": "Отзывы о развлечениях",
            },
        ),
    ]
