# Generated by Django 5.0.7 on 2024-07-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hotels', '0003_tag_hotel_content_hotel_date_hotel_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='images',
            field=models.ManyToManyField(related_name='hotels', to='core.image'),
        ),
    ]
