# Generated by Django 5.0.7 on 2024-09-17 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kashiring", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auto",
            name="body_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kashiring.bodytype",
                verbose_name="Кузов",
            ),
        ),
        migrations.AlterField(
            model_name="auto",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kashiring.brand",
                verbose_name="Брэнд",
            ),
        ),
        migrations.AlterField(
            model_name="auto",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kashiring.color",
                verbose_name="Цвет",
            ),
        ),
        migrations.AlterField(
            model_name="auto",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kashiring.model",
                verbose_name="Модель",
            ),
        ),
        migrations.AlterField(
            model_name="auto",
            name="year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kashiring.year",
                verbose_name="Год выпуска",
            ),
        ),
    ]
