# Generated by Django 5.0.7 on 2024-11-15 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0002_initial"),
        ("tours", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guide",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guides",
                to="regions.region",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewtour",
            name="owner",
            field=models.ForeignKey(
                default=1,
                help_text="Пользователь, оставивший отзыв.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец отзыва",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="geo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag",
                to="tours.geo",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tour",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag",
                to="tours.tag",
            ),
        ),
        migrations.AddField(
            model_name="reviewtour",
            name="tour",
            field=models.ForeignKey(
                help_text="Тур, к которому относится этот отзыв.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estimations",
                to="tours.tour",
                verbose_name="tour",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="tours.tour",
            ),
        ),
        migrations.AddField(
            model_name="gallerytour",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_tour",
                to="tours.tour",
            ),
        ),
        migrations.AddField(
            model_name="datetour",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="date_tour",
                to="tours.tour",
            ),
        ),
        migrations.AddField(
            model_name="tourconditions",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tourconditions",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tour_conditions",
                to="tours.tour",
            ),
        ),
        migrations.AddField(
            model_name="touroperator",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="touroperators",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="touroperator",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="touroperators",
                to="regions.region",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="tour_operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="touroperators",
                to="tours.touroperator",
            ),
        ),
    ]
