# Generated by Django 5.0.7 on 2024-10-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="image",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="url",
        ),
        migrations.AlterField(
            model_name="tour",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag",
                to="tours.tag",
            ),
        ),
    ]
