# Generated by Django 5.0.7 on 2024-08-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="slug",
        ),
        migrations.AddField(
            model_name="blog",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="content_images/"),
        ),
        migrations.AddField(
            model_name="blog",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="seo_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="seo_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="url",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
