# Generated by Django 5.0.7 on 2024-08-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_blog_photo_remove_blog_slug_blog_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(
                default=1, max_length=255, unique=True, verbose_name="slug"
            ),
            preserve_default=False,
        ),
    ]
