# Generated by Django 5.0.7 on 2024-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
