# Generated by Django 5.0.7 on 2024-07-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='url',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
