# Generated by Django 5.0.7 on 2024-07-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('regions', '0003_region_date_region_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='images',
            field=models.ManyToManyField(related_name='regions', to='core.image'),
        ),
    ]
