# Generated by Django 5.0.7 on 2024-07-17 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_region_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион/город', 'verbose_name_plural': 'Регионы/города'},
        ),
        migrations.RemoveField(
            model_name='region',
            name='images',
        ),
        migrations.CreateModel(
            name='RegionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='regions.region')),
            ],
        ),
    ]
