# Generated by Django 5.0.7 on 2024-07-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_attraction_content_attraction_date_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='images',
            field=models.ManyToManyField(related_name='attractions', to='core.image'),
        ),
    ]
